"""Generate the reviewed compact-storage migration and its data-preserving rollback.

No database connections. Re-run after changing the templates; review generated SQL.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MIGRATION = ROOT / "supabase/migrations/20260910122700_compact_ranking_storage.sql"
ROLLBACK = ROOT / "supabase/rollback/compact_ranking_storage.sql"
CONTRACT_HASHES = {
    "artist": "8424e781649a2c5d26a50c1de3493d95",
    "track": "3e17cf63eba8f3336af1e2496a956402",
    "album": "584bacf2dbedcf8ee9fb5fecb872d6cf",
}
# From the verified local restore and live schema, with pg_catalog,public search_path.
# Expression deparsing must not depend on a connection's default search_path.
# This deliberately fails closed on schema or
# policy drift, including added restrictive writes, column types and constraints.
CONTRACT_SIGNATURE = """md5(jsonb_build_object(
 'columns',(SELECT jsonb_agg(jsonb_build_array(a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull,a.attidentity,a.attgenerated,pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid=d.adrelid AND a.attnum=d.adnum WHERE a.attrelid='public.TABLE'::regclass AND a.attnum>0 AND NOT a.attisdropped),
 'constraints',(SELECT jsonb_agg(jsonb_build_array(c.contype,pg_get_constraintdef(c.oid),c.convalidated,c.condeferrable,c.condeferred) ORDER BY c.contype,pg_get_constraintdef(c.oid)) FROM pg_constraint c WHERE c.conrelid='public.TABLE'::regclass),
 'policies',(SELECT jsonb_agg(jsonb_build_array(p.polname,p.polcmd,p.polpermissive,(SELECT jsonb_agg(CASE WHEN x=0 THEN 'public' ELSE x::regrole::text END ORDER BY x::regrole::text) FROM unnest(p.polroles)x),pg_get_expr(p.polqual,p.polrelid),pg_get_expr(p.polwithcheck,p.polrelid)) ORDER BY p.polname) FROM pg_policy p WHERE p.polrelid='public.TABLE'::regclass),
 'rls',(SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid='public.TABLE'::regclass)
)::text)"""
KINDS = {
    "artist": {
        "meta": {"artist_id": "text NOT NULL", "artist_name": "text NOT NULL", "artist_image_url": "text", "genres": "text[]"},
        "values": {"popularity": "integer", "rank": "integer NOT NULL CHECK (rank BETWEEN 1 AND 50)", "previous_rank": "integer"},
        "columns": "id snapshot_id user_id artist_id artist_name artist_image_url genres popularity rank created_at previous_rank".split(),
    },
    "track": {
        "meta": {"track_id": "text NOT NULL", "track_name": "text NOT NULL", "track_image_url": "text", "artist_id": "text NOT NULL", "artist_name": "text NOT NULL", "album_id": "text NOT NULL", "album_name": "text NOT NULL", "duration_ms": "integer"},
        "values": {"popularity": "integer", "rank": "integer NOT NULL CHECK (rank BETWEEN 1 AND 50)", "previous_rank": "integer"},
        "columns": "id snapshot_id user_id track_id track_name track_image_url artist_id artist_name album_id album_name duration_ms popularity rank created_at previous_rank".split(),
    },
    "album": {
        "meta": {"album_id": "text NOT NULL", "album_name": "text NOT NULL", "album_image_url": "text", "artist_id": "text NOT NULL", "artist_name": "text NOT NULL", "release_date": "text", "total_tracks": "integer"},
        "values": {"track_count": "integer NOT NULL DEFAULT 1", "rank": "integer NOT NULL CHECK (rank >= 1)", "previous_rank": "integer"},
        "columns": "id snapshot_id user_id album_id album_name album_image_url artist_id artist_name release_date total_tracks track_count rank created_at previous_rank".split(),
    },
}

sql = ["""-- Generated by scripts/ranking-storage/generate.py. LOCAL REHEARSAL REQUIRED.
-- Apply during the documented maintenance window, with a verified backup.
BEGIN;
SET LOCAL search_path = pg_catalog, public;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '180s';
SELECT pg_advisory_xact_lock(hashtextextended('statsforspotify:maintenance-release',0));
LOCK TABLE public.snapshots IN SHARE ROW EXCLUSIVE MODE;
LOCK TABLE public.album_rankings, public.artist_rankings, public.track_rankings IN ACCESS EXCLUSIVE MODE;
CREATE SCHEMA ranking_storage AUTHORIZATION postgres;
CREATE SCHEMA ranking_storage_backup AUTHORIZATION postgres;
REVOKE ALL ON SCHEMA ranking_storage, ranking_storage_backup FROM PUBLIC, anon, authenticated, service_role;
COMMENT ON SCHEMA ranking_storage_backup IS 'Empty original table definitions for lossless rollback; never expose through the Data API.';
COMMENT ON SCHEMA ranking_storage IS 'Private versioned ranking storage; clients use the public security-invoker views.';

-- A definer trigger cannot use current_user to identify its caller. SET ROLE is
-- permission-checked by PostgreSQL, unlike user-editable JWT metadata.
CREATE FUNCTION ranking_storage.caller_bypasses_rls() RETURNS boolean
LANGUAGE sql STABLE SET search_path = pg_catalog, pg_temp AS $$
  SELECT coalesce((SELECT rolsuper OR rolbypassrls FROM pg_roles
    WHERE rolname = coalesce(nullif(current_setting('role',true),'none'),session_user)),false)
$$;
REVOKE ALL ON FUNCTION ranking_storage.caller_bypasses_rls() FROM PUBLIC;

-- Parent locks precede owner locks, so snapshot/account cascades cannot wait on
-- a writer that is itself waiting for those parents. Batches from the collectors
-- contain one owner/snapshot. Administrative imports must use that same boundary.
CREATE FUNCTION ranking_storage.lock_write(p_users uuid[], p_snapshots uuid[]) RETURNS void
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
DECLARE v_user uuid;
BEGIN
  PERFORM id FROM auth.users WHERE id=ANY(p_users) ORDER BY id FOR KEY SHARE;
  PERFORM id FROM public.snapshots WHERE id=ANY(p_snapshots) ORDER BY id FOR KEY SHARE;
  FOR v_user IN SELECT DISTINCT x FROM unnest(p_users) x WHERE x IS NOT NULL ORDER BY x LOOP
    PERFORM pg_advisory_xact_lock(hashtextextended('ranking-storage:'||v_user::text,0));
  END LOOP;
END $$;
REVOKE ALL ON FUNCTION ranking_storage.lock_write(uuid[],uuid[]) FROM PUBLIC;
"""]
rollback = ["""-- Restore original tables from CURRENT data, including writes since migration.
-- Rehearse locally; apply only in the same maintenance window as the forward change.
BEGIN;
SET LOCAL search_path = pg_catalog, public;
SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='180s';
SELECT pg_advisory_xact_lock(hashtextextended('statsforspotify:maintenance-release',0));
LOCK TABLE public.snapshots IN SHARE ROW EXCLUSIVE MODE;
LOCK TABLE ranking_storage.album_observations, ranking_storage.artist_observations,
  ranking_storage.track_observations IN ACCESS EXCLUSIVE MODE;
"""]

for kind, spec in KINDS.items():
    table = f"{kind}_rankings"
    meta = list(spec['meta'])
    values = list(spec['values'])
    columns = spec['columns']
    meta_csv = ', '.join(meta)
    params = ', '.join('p_'+name+' '+dtype.split()[0] for name,dtype in spec['meta'].items())
    fingerprint_args = ['p_'+name for name in meta] + (["array_dims(p_genres)"] if kind == 'artist' else [])
    view_cols = ', '.join(('m.' if name in meta else 'o.')+name for name in columns)
    new_meta = ', '.join('NEW.'+name for name in meta)
    equality = ' AND '.join(f'm.{name} IS NOT DISTINCT FROM NEW.{name}' for name in meta)
    source_equality = ' AND '.join(f'm.{name} IS NOT DISTINCT FROM r.{name}' for name in meta)
    obs_cols = ['id','snapshot_id','user_id','created_at','metadata_key']+values
    obs_insert_values = ['NEW.'+name if name!='metadata_key' else 'v_metadata' for name in obs_cols]
    expected_columns = "ARRAY["+', '.join("'"+c+"'" for c in columns)+"]::text[]"
    sql += [f"""
-- {kind}: fail closed on an already migrated or unexpected source contract.
DO $$ BEGIN
  IF {CONTRACT_SIGNATURE.replace('TABLE',table)} <> '{CONTRACT_HASHES[kind]}' THEN
    RAISE EXCEPTION 'Source schema or policies changed: {table}; re-audit before migrating';
  END IF;
  IF (SELECT relkind FROM pg_class WHERE oid='public.{table}'::regclass) <> 'r'
    OR (SELECT array_agg(attname::text ORDER BY attnum) FROM pg_attribute
        WHERE attrelid='public.{table}'::regclass AND attnum>0 AND NOT attisdropped) <> {expected_columns}
    OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='public.{table}'::regclass AND polcmd IN ('w','*'))
    OR EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='public.{table}'::regclass AND NOT tgisinternal)
    OR EXISTS(SELECT 1 FROM pg_constraint WHERE contype='f' AND confrelid='public.{table}'::regclass)
    OR EXISTS(SELECT 1 FROM pg_publication_tables WHERE schemaname='public' AND tablename='{table}')
    OR EXISTS(SELECT 1 FROM pg_depend d WHERE d.refclassid='pg_class'::regclass
       AND d.refobjid='public.{table}'::regclass AND d.classid IN ('pg_rewrite'::regclass,'pg_proc'::regclass))
    OR EXISTS(SELECT 1 FROM pg_depend d WHERE d.refclassid='pg_type'::regclass
       AND d.refobjid=(SELECT reltype FROM pg_class WHERE oid='public.{table}'::regclass)
       AND d.classid='pg_proc'::regclass)
  THEN RAISE EXCEPTION 'Unexpected {table} contract; inspect before migrating'; END IF;
END $$;
ALTER TABLE public.{table} SET SCHEMA ranking_storage_backup;

CREATE FUNCTION ranking_storage.{kind}_fingerprint({params}) RETURNS bytea
LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,pg_temp AS $$
 SELECT sha256(convert_to(jsonb_build_array({', '.join(fingerprint_args)})::text,'UTF8'))
$$;
REVOKE ALL ON FUNCTION ranking_storage.{kind}_fingerprint FROM PUBLIC;
ALTER FUNCTION ranking_storage.{kind}_fingerprint OWNER TO postgres;
CREATE TABLE ranking_storage.{kind}_metadata (
 metadata_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 {', '.join(name+' '+dtype for name,dtype in spec['meta'].items())},
 metadata_hash bytea GENERATED ALWAYS AS (ranking_storage.{kind}_fingerprint({meta_csv})) STORED,
 collision integer NOT NULL DEFAULT 0,
 UNIQUE (metadata_key,user_id), UNIQUE (user_id,metadata_hash,collision)
);
CREATE INDEX ON ranking_storage.{kind}_metadata(user_id,{kind}_id);
CREATE TABLE ranking_storage.{kind}_observations (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 snapshot_id uuid NOT NULL REFERENCES public.snapshots(id) ON DELETE CASCADE,
 user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 created_at timestamptz NOT NULL DEFAULT now(),
 metadata_key integer NOT NULL,
 {', '.join(name+' '+dtype for name,dtype in spec['values'].items())},
 FOREIGN KEY(metadata_key,user_id) REFERENCES ranking_storage.{kind}_metadata(metadata_key,user_id)
);
ALTER TABLE ranking_storage.{kind}_metadata OWNER TO postgres;
ALTER TABLE ranking_storage.{kind}_observations OWNER TO postgres;

-- Distinct typed metadata preserves NULLs and PostgreSQL array bounds. A digest
-- only selects a bucket; collisions use another discriminator, never wrong data.
INSERT INTO ranking_storage.{kind}_metadata(user_id,{meta_csv},collision)
 SELECT user_id,{meta_csv},(row_number() OVER (PARTITION BY user_id,
 ranking_storage.{kind}_fingerprint({meta_csv}))-1)::integer
 FROM (SELECT DISTINCT user_id,{meta_csv} FROM ranking_storage_backup.{table}) d;
INSERT INTO ranking_storage.{kind}_observations({', '.join(obs_cols)})
 SELECT {', '.join('m.metadata_key' if c=='metadata_key' else 'r.'+c for c in obs_cols)}
 FROM ranking_storage_backup.{table} r JOIN ranking_storage.{kind}_metadata m
 ON m.user_id=r.user_id AND m.metadata_hash=ranking_storage.{kind}_fingerprint({', '.join('r.'+c for c in meta)})
 AND {source_equality};

-- Build narrow indexes after the bulk copy. Repeated snapshot/owner/metadata
-- keys can use B-tree deduplication; sorting one snapshot's 50 rows is cheap.
ALTER TABLE ranking_storage.{kind}_observations ADD PRIMARY KEY(id);
CREATE INDEX ON ranking_storage.{kind}_observations(snapshot_id);
CREATE INDEX ON ranking_storage.{kind}_observations(user_id);
CREATE INDEX ON ranking_storage.{kind}_observations(metadata_key);

ALTER TABLE ranking_storage.{kind}_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE ranking_storage.{kind}_observations ENABLE ROW LEVEL SECURITY;
-- Preserve the exact live SELECT policies, including restrictive privacy rules.
DO $$ DECLARE p record; roles text; destination text;
BEGIN
 FOR p IN SELECT * FROM pg_policy WHERE polrelid='ranking_storage_backup.{table}'::regclass AND polcmd='r' LOOP
  SELECT string_agg(CASE WHEN x=0 THEN 'PUBLIC' ELSE quote_ident(x::regrole::text) END,',') INTO roles FROM unnest(p.polroles) x;
  FOREACH destination IN ARRAY ARRAY['{kind}_metadata','{kind}_observations'] LOOP
   EXECUTE format('CREATE POLICY %I ON ranking_storage.%I AS %s FOR SELECT TO %s USING (%s)',p.polname,destination,
    CASE WHEN p.polpermissive THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END,roles,pg_get_expr(p.polqual,p.polrelid));
  END LOOP;
 END LOOP;
END $$;
CREATE VIEW public.{table} WITH(security_invoker=true) AS
 SELECT {view_cols} FROM ranking_storage.{kind}_observations o
 JOIN ranking_storage.{kind}_metadata m ON m.metadata_key=o.metadata_key AND m.user_id=o.user_id;
ALTER VIEW public.{table} OWNER TO postgres;
GRANT SELECT ON ranking_storage.{kind}_metadata, ranking_storage.{kind}_observations TO anon,authenticated,service_role;
-- No schema USAGE or physical write grants to API roles. PostgreSQL resolves
-- the underlying view relations at creation; security-invoker RLS still applies.
DO $$ DECLARE d record; a record;
BEGIN
 FOR d IN SELECT attname,pg_get_expr(adbin,adrelid) AS expression FROM pg_attrdef JOIN pg_attribute
  ON adrelid=attrelid AND adnum=attnum WHERE adrelid='ranking_storage_backup.{table}'::regclass LOOP
  EXECUTE format('ALTER VIEW public.{table} ALTER COLUMN %I SET DEFAULT %s',d.attname,d.expression);
 END LOOP;
 FOR a IN SELECT x.* FROM pg_class c CROSS JOIN LATERAL aclexplode(c.relacl) x
  WHERE c.oid='ranking_storage_backup.{table}'::regclass LOOP
  EXECUTE format('GRANT %s ON public.{table} TO %s%s',a.privilege_type,
   CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE quote_ident(a.grantee::regrole::text) END,
   CASE WHEN a.is_grantable THEN ' WITH GRANT OPTION' ELSE '' END);
 END LOOP;
END $$;

CREATE FUNCTION ranking_storage.write_{kind}() RETURNS trigger
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
DECLARE v_privileged boolean := ranking_storage.caller_bypasses_rls();
 v_metadata integer; v_hash bytea; v_collision integer; v_id uuid;
 v_current public.{table}%ROWTYPE;
BEGIN
 IF current_setting('transaction_isolation') <> 'read committed' THEN
  RAISE EXCEPTION 'Ranking writes require READ COMMITTED isolation' USING ERRCODE='0A000';
 END IF;
 -- Match original INSERT/DELETE ownership and the absence of an UPDATE policy.
 IF NOT v_privileged THEN
  IF TG_OP='UPDATE' THEN RETURN NULL; END IF;
  IF TG_OP='DELETE' AND (auth.uid() IS NULL OR OLD.user_id IS DISTINCT FROM auth.uid()) THEN RETURN NULL; END IF;
  IF TG_OP='INSERT' AND (auth.uid() IS NULL OR NEW.user_id IS DISTINCT FROM auth.uid()) THEN
   RAISE EXCEPTION 'new row violates row-level security policy for {table}' USING ERRCODE='42501';
  END IF;
 END IF;
 PERFORM ranking_storage.lock_write(
  ARRAY[CASE WHEN TG_OP<>'DELETE' THEN NEW.user_id END,CASE WHEN TG_OP<>'INSERT' THEN OLD.user_id END],
  ARRAY[CASE WHEN TG_OP<>'DELETE' THEN NEW.snapshot_id END,CASE WHEN TG_OP<>'INSERT' THEN OLD.snapshot_id END]);
 IF TG_OP IN ('DELETE','UPDATE') THEN
  SELECT {view_cols} INTO v_current FROM ranking_storage.{kind}_observations o
   JOIN ranking_storage.{kind}_metadata m ON m.metadata_key=o.metadata_key AND m.user_id=o.user_id
   WHERE o.id=OLD.id FOR UPDATE OF o;
  IF NOT FOUND THEN RETURN NULL; END IF;
  IF v_current IS DISTINCT FROM OLD THEN
   RAISE EXCEPTION 'Ranking changed concurrently; retry transaction' USING ERRCODE='40001';
  END IF;
 END IF;
 IF TG_OP='DELETE' THEN
  DELETE FROM ranking_storage.{kind}_observations WHERE id=OLD.id RETURNING id INTO v_id;
  IF v_id IS NULL THEN RETURN NULL; END IF;
  RETURN OLD;
 END IF;
 v_hash := ranking_storage.{kind}_fingerprint({new_meta});
 -- Separate statement after the lock gives a fresh READ COMMITTED snapshot.
 SELECT metadata_key INTO v_metadata FROM ranking_storage.{kind}_metadata m
 WHERE m.user_id=NEW.user_id AND m.metadata_hash=v_hash AND {equality};
 IF v_metadata IS NULL THEN
  SELECT coalesce(max(collision)+1,0) INTO v_collision FROM ranking_storage.{kind}_metadata
   WHERE user_id=NEW.user_id AND metadata_hash=v_hash;
  BEGIN
   INSERT INTO ranking_storage.{kind}_metadata(user_id,{meta_csv},collision)
   VALUES(NEW.user_id,{new_meta},v_collision) RETURNING metadata_key INTO v_metadata;
  EXCEPTION WHEN unique_violation THEN
   -- Fail atomically if a concurrent administrative writer bypasses this lock.
   RAISE EXCEPTION 'concurrent metadata change; retry transaction' USING ERRCODE='40001';
  END;
 END IF;
 IF TG_OP='INSERT' THEN
  INSERT INTO ranking_storage.{kind}_observations({', '.join(obs_cols)}) VALUES({', '.join(obs_insert_values)});
 ELSE
  UPDATE ranking_storage.{kind}_observations SET {', '.join(c+'='+v for c,v in zip(obs_cols,obs_insert_values))} WHERE id=OLD.id RETURNING id INTO v_id;
  IF v_id IS NULL THEN RETURN NULL; END IF;
 END IF;
 RETURN NEW;
END $$;
ALTER FUNCTION ranking_storage.write_{kind}() OWNER TO postgres;
REVOKE ALL ON FUNCTION ranking_storage.write_{kind}() FROM PUBLIC;
CREATE TRIGGER write_{kind}_ranking INSTEAD OF INSERT OR UPDATE OR DELETE ON public.{table}
 FOR EACH ROW EXECUTE FUNCTION ranking_storage.write_{kind}();

CREATE FUNCTION ranking_storage.prune_{kind}() RETURNS trigger
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
BEGIN
 IF current_setting('transaction_isolation') <> 'read committed' THEN
  RAISE EXCEPTION 'Ranking deletion requires READ COMMITTED isolation' USING ERRCODE='0A000';
 END IF;
 IF TG_OP='UPDATE' AND OLD.metadata_key=NEW.metadata_key AND OLD.user_id=NEW.user_id THEN RETURN NULL; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('ranking-storage:'||OLD.user_id::text,0));
 DELETE FROM ranking_storage.{kind}_metadata m WHERE m.metadata_key=OLD.metadata_key
 AND NOT EXISTS(SELECT 1 FROM ranking_storage.{kind}_observations o WHERE o.metadata_key=m.metadata_key);
 RETURN NULL;
END $$;
ALTER FUNCTION ranking_storage.prune_{kind}() OWNER TO postgres;
REVOKE ALL ON FUNCTION ranking_storage.prune_{kind}() FROM PUBLIC;
CREATE TRIGGER prune_{kind}_metadata AFTER DELETE OR UPDATE ON ranking_storage.{kind}_observations
 FOR EACH ROW EXECUTE FUNCTION ranking_storage.prune_{kind}();

DO $$ BEGIN
 IF EXISTS((SELECT * FROM ranking_storage_backup.{table} EXCEPT ALL SELECT * FROM public.{table})
  UNION ALL (SELECT * FROM public.{table} EXCEPT ALL SELECT * FROM ranking_storage_backup.{table}))
 THEN RAISE EXCEPTION 'Exact reconstruction failed: {table}'; END IF;
END $$;
"""]
    rollback += [f"""
-- The original table is an empty definition template; never overwrite old data.
DO $$ BEGIN IF EXISTS(SELECT 1 FROM ranking_storage_backup.{table}) THEN
 RAISE EXCEPTION 'Rollback template {table} is not empty'; END IF; END $$;
INSERT INTO ranking_storage_backup.{table} SELECT * FROM public.{table};
DO $$ BEGIN IF EXISTS((SELECT * FROM ranking_storage_backup.{table} EXCEPT ALL SELECT * FROM public.{table})
 UNION ALL (SELECT * FROM public.{table} EXCEPT ALL SELECT * FROM ranking_storage_backup.{table}))
 THEN RAISE EXCEPTION 'Rollback reconstruction failed: {table}'; END IF; END $$;
DROP VIEW public.{table};
ALTER TABLE ranking_storage_backup.{table} SET SCHEMA public;
DROP TABLE ranking_storage.{kind}_observations;
DROP TABLE ranking_storage.{kind}_metadata;
DROP FUNCTION ranking_storage.write_{kind}();
DROP FUNCTION ranking_storage.prune_{kind}();
DROP FUNCTION ranking_storage.{kind}_fingerprint;
"""]

sql += ["""
-- Free old data only after all tables passed typed, bidirectional equality.
TRUNCATE ranking_storage_backup.album_rankings,ranking_storage_backup.artist_rankings,ranking_storage_backup.track_rankings;
ALTER FUNCTION ranking_storage.lock_write(uuid[],uuid[]) OWNER TO postgres;
ALTER FUNCTION ranking_storage.caller_bypasses_rls() OWNER TO postgres;
ANALYZE ranking_storage.album_observations; ANALYZE ranking_storage.artist_observations; ANALYZE ranking_storage.track_observations;
ANALYZE ranking_storage.album_metadata; ANALYZE ranking_storage.artist_metadata; ANALYZE ranking_storage.track_metadata;
NOTIFY pgrst,'reload schema';
COMMIT;
"""]
rollback += ["""
DROP FUNCTION ranking_storage.lock_write(uuid[],uuid[]);
DROP FUNCTION ranking_storage.caller_bypasses_rls();
DROP SCHEMA ranking_storage;
DROP SCHEMA ranking_storage_backup;
ANALYZE public.album_rankings; ANALYZE public.artist_rankings; ANALYZE public.track_rankings;
NOTIFY pgrst,'reload schema';
COMMIT;
"""]
MIGRATION.write_text('\n'.join(sql),encoding='utf-8')
ROLLBACK.parent.mkdir(parents=True,exist_ok=True)
ROLLBACK.write_text('\n'.join(rollback),encoding='utf-8')
print(f"Generated {MIGRATION.name} and rollback")
