-- Generated by scripts/ranking-storage/generate.py. LOCAL REHEARSAL REQUIRED.
-- Apply during the documented maintenance window, with a verified backup.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '180s';
SELECT pg_advisory_xact_lock(hashtextextended('statsforspotify:maintenance-release',0));
LOCK TABLE public.snapshots IN SHARE ROW EXCLUSIVE MODE;
LOCK TABLE public.album_rankings, public.artist_rankings, public.track_rankings IN ACCESS EXCLUSIVE MODE;
CREATE SCHEMA ranking_storage AUTHORIZATION postgres;
CREATE SCHEMA ranking_storage_backup AUTHORIZATION postgres;
REVOKE ALL ON SCHEMA ranking_storage, ranking_storage_backup FROM PUBLIC, anon, authenticated, service_role;
COMMENT ON SCHEMA ranking_storage_backup IS 'Empty original table definitions for lossless rollback; never expose through the Data API.';
COMMENT ON SCHEMA ranking_storage IS 'Private versioned ranking storage; clients use the public security-invoker views.';

-- A definer trigger cannot use current_user to identify its caller. SET ROLE is
-- permission-checked by PostgreSQL, unlike user-editable JWT metadata.
CREATE FUNCTION ranking_storage.caller_bypasses_rls() RETURNS boolean
LANGUAGE sql STABLE SET search_path = pg_catalog, pg_temp AS $$
  SELECT coalesce((SELECT rolsuper OR rolbypassrls FROM pg_roles
    WHERE rolname = coalesce(nullif(current_setting('role',true),'none'),session_user)),false)
$$;
REVOKE ALL ON FUNCTION ranking_storage.caller_bypasses_rls() FROM PUBLIC;

-- Parent locks precede owner locks, so snapshot/account cascades cannot wait on
-- a writer that is itself waiting for those parents. Batches from the collectors
-- contain one owner/snapshot. Administrative imports must use that same boundary.
CREATE FUNCTION ranking_storage.lock_write(p_users uuid[], p_snapshots uuid[]) RETURNS void
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
DECLARE v_user uuid;
BEGIN
  PERFORM id FROM auth.users WHERE id=ANY(p_users) ORDER BY id FOR KEY SHARE;
  PERFORM id FROM public.snapshots WHERE id=ANY(p_snapshots) ORDER BY id FOR KEY SHARE;
  FOR v_user IN SELECT DISTINCT x FROM unnest(p_users) x WHERE x IS NOT NULL ORDER BY x LOOP
    PERFORM pg_advisory_xact_lock(hashtextextended('ranking-storage:'||v_user::text,0));
  END LOOP;
END $$;
REVOKE ALL ON FUNCTION ranking_storage.lock_write(uuid[],uuid[]) FROM PUBLIC;


-- artist: fail closed on an already migrated or unexpected source contract.
DO $$ BEGIN
  IF md5(jsonb_build_object(
 'columns',(SELECT jsonb_agg(jsonb_build_array(a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull,a.attidentity,a.attgenerated,pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid=d.adrelid AND a.attnum=d.adnum WHERE a.attrelid='public.artist_rankings'::regclass AND a.attnum>0 AND NOT a.attisdropped),
 'constraints',(SELECT jsonb_agg(jsonb_build_array(c.contype,pg_get_constraintdef(c.oid),c.convalidated,c.condeferrable,c.condeferred) ORDER BY c.contype,pg_get_constraintdef(c.oid)) FROM pg_constraint c WHERE c.conrelid='public.artist_rankings'::regclass),
 'policies',(SELECT jsonb_agg(jsonb_build_array(p.polname,p.polcmd,p.polpermissive,(SELECT jsonb_agg(CASE WHEN x=0 THEN 'public' ELSE x::regrole::text END ORDER BY x::regrole::text) FROM unnest(p.polroles)x),pg_get_expr(p.polqual,p.polrelid),pg_get_expr(p.polwithcheck,p.polrelid)) ORDER BY p.polname) FROM pg_policy p WHERE p.polrelid='public.artist_rankings'::regclass),
 'rls',(SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid='public.artist_rankings'::regclass)
)::text) <> '2d6d7b0bc4db1ea932a2469ce26ac5c9' THEN
    RAISE EXCEPTION 'Source schema or policies changed: artist_rankings; re-audit before migrating';
  END IF;
  IF (SELECT relkind FROM pg_class WHERE oid='public.artist_rankings'::regclass) <> 'r'
    OR (SELECT array_agg(attname::text ORDER BY attnum) FROM pg_attribute
        WHERE attrelid='public.artist_rankings'::regclass AND attnum>0 AND NOT attisdropped) <> ARRAY['id', 'snapshot_id', 'user_id', 'artist_id', 'artist_name', 'artist_image_url', 'genres', 'popularity', 'rank', 'created_at', 'previous_rank']::text[]
    OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='public.artist_rankings'::regclass AND polcmd IN ('w','*'))
    OR EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='public.artist_rankings'::regclass AND NOT tgisinternal)
    OR EXISTS(SELECT 1 FROM pg_constraint WHERE contype='f' AND confrelid='public.artist_rankings'::regclass)
    OR EXISTS(SELECT 1 FROM pg_publication_tables WHERE schemaname='public' AND tablename='artist_rankings')
    OR EXISTS(SELECT 1 FROM pg_depend d WHERE d.refclassid='pg_class'::regclass
       AND d.refobjid='public.artist_rankings'::regclass AND d.classid IN ('pg_rewrite'::regclass,'pg_proc'::regclass))
    OR EXISTS(SELECT 1 FROM pg_depend d WHERE d.refclassid='pg_type'::regclass
       AND d.refobjid=(SELECT reltype FROM pg_class WHERE oid='public.artist_rankings'::regclass)
       AND d.classid='pg_proc'::regclass)
  THEN RAISE EXCEPTION 'Unexpected artist_rankings contract; inspect before migrating'; END IF;
END $$;
ALTER TABLE public.artist_rankings SET SCHEMA ranking_storage_backup;

CREATE FUNCTION ranking_storage.artist_fingerprint(p_artist_id text, p_artist_name text, p_artist_image_url text, p_genres text[]) RETURNS bytea
LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,pg_temp AS $$
 SELECT sha256(convert_to(jsonb_build_array(p_artist_id, p_artist_name, p_artist_image_url, p_genres, array_dims(p_genres))::text,'UTF8'))
$$;
REVOKE ALL ON FUNCTION ranking_storage.artist_fingerprint FROM PUBLIC;
ALTER FUNCTION ranking_storage.artist_fingerprint OWNER TO postgres;
CREATE TABLE ranking_storage.artist_metadata (
 metadata_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 artist_id text NOT NULL, artist_name text NOT NULL, artist_image_url text, genres text[],
 metadata_hash bytea GENERATED ALWAYS AS (ranking_storage.artist_fingerprint(artist_id, artist_name, artist_image_url, genres)) STORED,
 collision integer NOT NULL DEFAULT 0,
 UNIQUE (metadata_key,user_id), UNIQUE (user_id,metadata_hash,collision)
);
CREATE INDEX ON ranking_storage.artist_metadata(user_id,artist_id);
CREATE TABLE ranking_storage.artist_observations (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 snapshot_id uuid NOT NULL REFERENCES public.snapshots(id) ON DELETE CASCADE,
 user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 created_at timestamptz NOT NULL DEFAULT now(),
 metadata_key integer NOT NULL,
 popularity integer, rank integer NOT NULL CHECK (rank BETWEEN 1 AND 50), previous_rank integer,
 FOREIGN KEY(metadata_key,user_id) REFERENCES ranking_storage.artist_metadata(metadata_key,user_id)
);
ALTER TABLE ranking_storage.artist_metadata OWNER TO postgres;
ALTER TABLE ranking_storage.artist_observations OWNER TO postgres;

-- Distinct typed metadata preserves NULLs and PostgreSQL array bounds. A digest
-- only selects a bucket; collisions use another discriminator, never wrong data.
INSERT INTO ranking_storage.artist_metadata(user_id,artist_id, artist_name, artist_image_url, genres,collision)
 SELECT user_id,artist_id, artist_name, artist_image_url, genres,(row_number() OVER (PARTITION BY user_id,
 ranking_storage.artist_fingerprint(artist_id, artist_name, artist_image_url, genres))-1)::integer
 FROM (SELECT DISTINCT user_id,artist_id, artist_name, artist_image_url, genres FROM ranking_storage_backup.artist_rankings) d;
INSERT INTO ranking_storage.artist_observations(id, snapshot_id, user_id, created_at, metadata_key, popularity, rank, previous_rank)
 SELECT r.id, r.snapshot_id, r.user_id, r.created_at, m.metadata_key, r.popularity, r.rank, r.previous_rank
 FROM ranking_storage_backup.artist_rankings r JOIN ranking_storage.artist_metadata m
 ON m.user_id=r.user_id AND m.metadata_hash=ranking_storage.artist_fingerprint(r.artist_id, r.artist_name, r.artist_image_url, r.genres)
 AND m.artist_id IS NOT DISTINCT FROM r.artist_id AND m.artist_name IS NOT DISTINCT FROM r.artist_name AND m.artist_image_url IS NOT DISTINCT FROM r.artist_image_url AND m.genres IS NOT DISTINCT FROM r.genres;

-- Build narrow indexes after the bulk copy. Repeated snapshot/owner/metadata
-- keys can use B-tree deduplication; sorting one snapshot's 50 rows is cheap.
ALTER TABLE ranking_storage.artist_observations ADD PRIMARY KEY(id);
CREATE INDEX ON ranking_storage.artist_observations(snapshot_id);
CREATE INDEX ON ranking_storage.artist_observations(user_id);
CREATE INDEX ON ranking_storage.artist_observations(metadata_key);

ALTER TABLE ranking_storage.artist_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE ranking_storage.artist_observations ENABLE ROW LEVEL SECURITY;
-- Preserve the exact live SELECT policies, including restrictive privacy rules.
DO $$ DECLARE p record; roles text; destination text;
BEGIN
 FOR p IN SELECT * FROM pg_policy WHERE polrelid='ranking_storage_backup.artist_rankings'::regclass AND polcmd='r' LOOP
  SELECT string_agg(CASE WHEN x=0 THEN 'PUBLIC' ELSE quote_ident(x::regrole::text) END,',') INTO roles FROM unnest(p.polroles) x;
  FOREACH destination IN ARRAY ARRAY['artist_metadata','artist_observations'] LOOP
   EXECUTE format('CREATE POLICY %I ON ranking_storage.%I AS %s FOR SELECT TO %s USING (%s)',p.polname,destination,
    CASE WHEN p.polpermissive THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END,roles,pg_get_expr(p.polqual,p.polrelid));
  END LOOP;
 END LOOP;
END $$;
CREATE VIEW public.artist_rankings WITH(security_invoker=true) AS
 SELECT o.id, o.snapshot_id, o.user_id, m.artist_id, m.artist_name, m.artist_image_url, m.genres, o.popularity, o.rank, o.created_at, o.previous_rank FROM ranking_storage.artist_observations o
 JOIN ranking_storage.artist_metadata m ON m.metadata_key=o.metadata_key AND m.user_id=o.user_id;
ALTER VIEW public.artist_rankings OWNER TO postgres;
GRANT SELECT ON ranking_storage.artist_metadata, ranking_storage.artist_observations TO anon,authenticated,service_role;
-- No schema USAGE or physical write grants to API roles. PostgreSQL resolves
-- the underlying view relations at creation; security-invoker RLS still applies.
DO $$ DECLARE d record; a record;
BEGIN
 FOR d IN SELECT attname,pg_get_expr(adbin,adrelid) AS expression FROM pg_attrdef JOIN pg_attribute
  ON adrelid=attrelid AND adnum=attnum WHERE adrelid='ranking_storage_backup.artist_rankings'::regclass LOOP
  EXECUTE format('ALTER VIEW public.artist_rankings ALTER COLUMN %I SET DEFAULT %s',d.attname,d.expression);
 END LOOP;
 FOR a IN SELECT x.* FROM pg_class c CROSS JOIN LATERAL aclexplode(c.relacl) x
  WHERE c.oid='ranking_storage_backup.artist_rankings'::regclass LOOP
  EXECUTE format('GRANT %s ON public.artist_rankings TO %s%s',a.privilege_type,
   CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE quote_ident(a.grantee::regrole::text) END,
   CASE WHEN a.is_grantable THEN ' WITH GRANT OPTION' ELSE '' END);
 END LOOP;
END $$;

CREATE FUNCTION ranking_storage.write_artist() RETURNS trigger
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
DECLARE v_privileged boolean := ranking_storage.caller_bypasses_rls();
 v_metadata integer; v_hash bytea; v_collision integer; v_id uuid;
 v_current public.artist_rankings%ROWTYPE;
BEGIN
 IF current_setting('transaction_isolation') <> 'read committed' THEN
  RAISE EXCEPTION 'Ranking writes require READ COMMITTED isolation' USING ERRCODE='0A000';
 END IF;
 -- Match original INSERT/DELETE ownership and the absence of an UPDATE policy.
 IF NOT v_privileged THEN
  IF TG_OP='UPDATE' THEN RETURN NULL; END IF;
  IF TG_OP='DELETE' AND (auth.uid() IS NULL OR OLD.user_id IS DISTINCT FROM auth.uid()) THEN RETURN NULL; END IF;
  IF TG_OP='INSERT' AND (auth.uid() IS NULL OR NEW.user_id IS DISTINCT FROM auth.uid()) THEN
   RAISE EXCEPTION 'new row violates row-level security policy for artist_rankings' USING ERRCODE='42501';
  END IF;
 END IF;
 PERFORM ranking_storage.lock_write(
  ARRAY[CASE WHEN TG_OP<>'DELETE' THEN NEW.user_id END,CASE WHEN TG_OP<>'INSERT' THEN OLD.user_id END],
  ARRAY[CASE WHEN TG_OP<>'DELETE' THEN NEW.snapshot_id END,CASE WHEN TG_OP<>'INSERT' THEN OLD.snapshot_id END]);
 IF TG_OP IN ('DELETE','UPDATE') THEN
  SELECT o.id, o.snapshot_id, o.user_id, m.artist_id, m.artist_name, m.artist_image_url, m.genres, o.popularity, o.rank, o.created_at, o.previous_rank INTO v_current FROM ranking_storage.artist_observations o
   JOIN ranking_storage.artist_metadata m ON m.metadata_key=o.metadata_key AND m.user_id=o.user_id
   WHERE o.id=OLD.id FOR UPDATE OF o;
  IF NOT FOUND THEN RETURN NULL; END IF;
  IF v_current IS DISTINCT FROM OLD THEN
   RAISE EXCEPTION 'Ranking changed concurrently; retry transaction' USING ERRCODE='40001';
  END IF;
 END IF;
 IF TG_OP='DELETE' THEN
  DELETE FROM ranking_storage.artist_observations WHERE id=OLD.id RETURNING id INTO v_id;
  IF v_id IS NULL THEN RETURN NULL; END IF;
  RETURN OLD;
 END IF;
 v_hash := ranking_storage.artist_fingerprint(NEW.artist_id, NEW.artist_name, NEW.artist_image_url, NEW.genres);
 -- Separate statement after the lock gives a fresh READ COMMITTED snapshot.
 SELECT metadata_key INTO v_metadata FROM ranking_storage.artist_metadata m
 WHERE m.user_id=NEW.user_id AND m.metadata_hash=v_hash AND m.artist_id IS NOT DISTINCT FROM NEW.artist_id AND m.artist_name IS NOT DISTINCT FROM NEW.artist_name AND m.artist_image_url IS NOT DISTINCT FROM NEW.artist_image_url AND m.genres IS NOT DISTINCT FROM NEW.genres;
 IF v_metadata IS NULL THEN
  SELECT coalesce(max(collision)+1,0) INTO v_collision FROM ranking_storage.artist_metadata
   WHERE user_id=NEW.user_id AND metadata_hash=v_hash;
  BEGIN
   INSERT INTO ranking_storage.artist_metadata(user_id,artist_id, artist_name, artist_image_url, genres,collision)
   VALUES(NEW.user_id,NEW.artist_id, NEW.artist_name, NEW.artist_image_url, NEW.genres,v_collision) RETURNING metadata_key INTO v_metadata;
  EXCEPTION WHEN unique_violation THEN
   -- Fail atomically if a concurrent administrative writer bypasses this lock.
   RAISE EXCEPTION 'concurrent metadata change; retry transaction' USING ERRCODE='40001';
  END;
 END IF;
 IF TG_OP='INSERT' THEN
  INSERT INTO ranking_storage.artist_observations(id, snapshot_id, user_id, created_at, metadata_key, popularity, rank, previous_rank) VALUES(NEW.id, NEW.snapshot_id, NEW.user_id, NEW.created_at, v_metadata, NEW.popularity, NEW.rank, NEW.previous_rank);
 ELSE
  UPDATE ranking_storage.artist_observations SET id=NEW.id, snapshot_id=NEW.snapshot_id, user_id=NEW.user_id, created_at=NEW.created_at, metadata_key=v_metadata, popularity=NEW.popularity, rank=NEW.rank, previous_rank=NEW.previous_rank WHERE id=OLD.id RETURNING id INTO v_id;
  IF v_id IS NULL THEN RETURN NULL; END IF;
 END IF;
 RETURN NEW;
END $$;
ALTER FUNCTION ranking_storage.write_artist() OWNER TO postgres;
REVOKE ALL ON FUNCTION ranking_storage.write_artist() FROM PUBLIC;
CREATE TRIGGER write_artist_ranking INSTEAD OF INSERT OR UPDATE OR DELETE ON public.artist_rankings
 FOR EACH ROW EXECUTE FUNCTION ranking_storage.write_artist();

CREATE FUNCTION ranking_storage.prune_artist() RETURNS trigger
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
BEGIN
 IF current_setting('transaction_isolation') <> 'read committed' THEN
  RAISE EXCEPTION 'Ranking deletion requires READ COMMITTED isolation' USING ERRCODE='0A000';
 END IF;
 IF TG_OP='UPDATE' AND OLD.metadata_key=NEW.metadata_key AND OLD.user_id=NEW.user_id THEN RETURN NULL; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('ranking-storage:'||OLD.user_id::text,0));
 DELETE FROM ranking_storage.artist_metadata m WHERE m.metadata_key=OLD.metadata_key
 AND NOT EXISTS(SELECT 1 FROM ranking_storage.artist_observations o WHERE o.metadata_key=m.metadata_key);
 RETURN NULL;
END $$;
ALTER FUNCTION ranking_storage.prune_artist() OWNER TO postgres;
REVOKE ALL ON FUNCTION ranking_storage.prune_artist() FROM PUBLIC;
CREATE TRIGGER prune_artist_metadata AFTER DELETE OR UPDATE ON ranking_storage.artist_observations
 FOR EACH ROW EXECUTE FUNCTION ranking_storage.prune_artist();

DO $$ BEGIN
 IF EXISTS((SELECT * FROM ranking_storage_backup.artist_rankings EXCEPT ALL SELECT * FROM public.artist_rankings)
  UNION ALL (SELECT * FROM public.artist_rankings EXCEPT ALL SELECT * FROM ranking_storage_backup.artist_rankings))
 THEN RAISE EXCEPTION 'Exact reconstruction failed: artist_rankings'; END IF;
END $$;


-- track: fail closed on an already migrated or unexpected source contract.
DO $$ BEGIN
  IF md5(jsonb_build_object(
 'columns',(SELECT jsonb_agg(jsonb_build_array(a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull,a.attidentity,a.attgenerated,pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid=d.adrelid AND a.attnum=d.adnum WHERE a.attrelid='public.track_rankings'::regclass AND a.attnum>0 AND NOT a.attisdropped),
 'constraints',(SELECT jsonb_agg(jsonb_build_array(c.contype,pg_get_constraintdef(c.oid),c.convalidated,c.condeferrable,c.condeferred) ORDER BY c.contype,pg_get_constraintdef(c.oid)) FROM pg_constraint c WHERE c.conrelid='public.track_rankings'::regclass),
 'policies',(SELECT jsonb_agg(jsonb_build_array(p.polname,p.polcmd,p.polpermissive,(SELECT jsonb_agg(CASE WHEN x=0 THEN 'public' ELSE x::regrole::text END ORDER BY x::regrole::text) FROM unnest(p.polroles)x),pg_get_expr(p.polqual,p.polrelid),pg_get_expr(p.polwithcheck,p.polrelid)) ORDER BY p.polname) FROM pg_policy p WHERE p.polrelid='public.track_rankings'::regclass),
 'rls',(SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid='public.track_rankings'::regclass)
)::text) <> '94400b4d025b1c7cc55106877546ee58' THEN
    RAISE EXCEPTION 'Source schema or policies changed: track_rankings; re-audit before migrating';
  END IF;
  IF (SELECT relkind FROM pg_class WHERE oid='public.track_rankings'::regclass) <> 'r'
    OR (SELECT array_agg(attname::text ORDER BY attnum) FROM pg_attribute
        WHERE attrelid='public.track_rankings'::regclass AND attnum>0 AND NOT attisdropped) <> ARRAY['id', 'snapshot_id', 'user_id', 'track_id', 'track_name', 'track_image_url', 'artist_id', 'artist_name', 'album_id', 'album_name', 'duration_ms', 'popularity', 'rank', 'created_at', 'previous_rank']::text[]
    OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='public.track_rankings'::regclass AND polcmd IN ('w','*'))
    OR EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='public.track_rankings'::regclass AND NOT tgisinternal)
    OR EXISTS(SELECT 1 FROM pg_constraint WHERE contype='f' AND confrelid='public.track_rankings'::regclass)
    OR EXISTS(SELECT 1 FROM pg_publication_tables WHERE schemaname='public' AND tablename='track_rankings')
    OR EXISTS(SELECT 1 FROM pg_depend d WHERE d.refclassid='pg_class'::regclass
       AND d.refobjid='public.track_rankings'::regclass AND d.classid IN ('pg_rewrite'::regclass,'pg_proc'::regclass))
    OR EXISTS(SELECT 1 FROM pg_depend d WHERE d.refclassid='pg_type'::regclass
       AND d.refobjid=(SELECT reltype FROM pg_class WHERE oid='public.track_rankings'::regclass)
       AND d.classid='pg_proc'::regclass)
  THEN RAISE EXCEPTION 'Unexpected track_rankings contract; inspect before migrating'; END IF;
END $$;
ALTER TABLE public.track_rankings SET SCHEMA ranking_storage_backup;

CREATE FUNCTION ranking_storage.track_fingerprint(p_track_id text, p_track_name text, p_track_image_url text, p_artist_id text, p_artist_name text, p_album_id text, p_album_name text, p_duration_ms integer) RETURNS bytea
LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,pg_temp AS $$
 SELECT sha256(convert_to(jsonb_build_array(p_track_id, p_track_name, p_track_image_url, p_artist_id, p_artist_name, p_album_id, p_album_name, p_duration_ms)::text,'UTF8'))
$$;
REVOKE ALL ON FUNCTION ranking_storage.track_fingerprint FROM PUBLIC;
ALTER FUNCTION ranking_storage.track_fingerprint OWNER TO postgres;
CREATE TABLE ranking_storage.track_metadata (
 metadata_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 track_id text NOT NULL, track_name text NOT NULL, track_image_url text, artist_id text NOT NULL, artist_name text NOT NULL, album_id text NOT NULL, album_name text NOT NULL, duration_ms integer,
 metadata_hash bytea GENERATED ALWAYS AS (ranking_storage.track_fingerprint(track_id, track_name, track_image_url, artist_id, artist_name, album_id, album_name, duration_ms)) STORED,
 collision integer NOT NULL DEFAULT 0,
 UNIQUE (metadata_key,user_id), UNIQUE (user_id,metadata_hash,collision)
);
CREATE INDEX ON ranking_storage.track_metadata(user_id,track_id);
CREATE TABLE ranking_storage.track_observations (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 snapshot_id uuid NOT NULL REFERENCES public.snapshots(id) ON DELETE CASCADE,
 user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 created_at timestamptz NOT NULL DEFAULT now(),
 metadata_key integer NOT NULL,
 popularity integer, rank integer NOT NULL CHECK (rank BETWEEN 1 AND 50), previous_rank integer,
 FOREIGN KEY(metadata_key,user_id) REFERENCES ranking_storage.track_metadata(metadata_key,user_id)
);
ALTER TABLE ranking_storage.track_metadata OWNER TO postgres;
ALTER TABLE ranking_storage.track_observations OWNER TO postgres;

-- Distinct typed metadata preserves NULLs and PostgreSQL array bounds. A digest
-- only selects a bucket; collisions use another discriminator, never wrong data.
INSERT INTO ranking_storage.track_metadata(user_id,track_id, track_name, track_image_url, artist_id, artist_name, album_id, album_name, duration_ms,collision)
 SELECT user_id,track_id, track_name, track_image_url, artist_id, artist_name, album_id, album_name, duration_ms,(row_number() OVER (PARTITION BY user_id,
 ranking_storage.track_fingerprint(track_id, track_name, track_image_url, artist_id, artist_name, album_id, album_name, duration_ms))-1)::integer
 FROM (SELECT DISTINCT user_id,track_id, track_name, track_image_url, artist_id, artist_name, album_id, album_name, duration_ms FROM ranking_storage_backup.track_rankings) d;
INSERT INTO ranking_storage.track_observations(id, snapshot_id, user_id, created_at, metadata_key, popularity, rank, previous_rank)
 SELECT r.id, r.snapshot_id, r.user_id, r.created_at, m.metadata_key, r.popularity, r.rank, r.previous_rank
 FROM ranking_storage_backup.track_rankings r JOIN ranking_storage.track_metadata m
 ON m.user_id=r.user_id AND m.metadata_hash=ranking_storage.track_fingerprint(r.track_id, r.track_name, r.track_image_url, r.artist_id, r.artist_name, r.album_id, r.album_name, r.duration_ms)
 AND m.track_id IS NOT DISTINCT FROM r.track_id AND m.track_name IS NOT DISTINCT FROM r.track_name AND m.track_image_url IS NOT DISTINCT FROM r.track_image_url AND m.artist_id IS NOT DISTINCT FROM r.artist_id AND m.artist_name IS NOT DISTINCT FROM r.artist_name AND m.album_id IS NOT DISTINCT FROM r.album_id AND m.album_name IS NOT DISTINCT FROM r.album_name AND m.duration_ms IS NOT DISTINCT FROM r.duration_ms;

-- Build narrow indexes after the bulk copy. Repeated snapshot/owner/metadata
-- keys can use B-tree deduplication; sorting one snapshot's 50 rows is cheap.
ALTER TABLE ranking_storage.track_observations ADD PRIMARY KEY(id);
CREATE INDEX ON ranking_storage.track_observations(snapshot_id);
CREATE INDEX ON ranking_storage.track_observations(user_id);
CREATE INDEX ON ranking_storage.track_observations(metadata_key);

ALTER TABLE ranking_storage.track_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE ranking_storage.track_observations ENABLE ROW LEVEL SECURITY;
-- Preserve the exact live SELECT policies, including restrictive privacy rules.
DO $$ DECLARE p record; roles text; destination text;
BEGIN
 FOR p IN SELECT * FROM pg_policy WHERE polrelid='ranking_storage_backup.track_rankings'::regclass AND polcmd='r' LOOP
  SELECT string_agg(CASE WHEN x=0 THEN 'PUBLIC' ELSE quote_ident(x::regrole::text) END,',') INTO roles FROM unnest(p.polroles) x;
  FOREACH destination IN ARRAY ARRAY['track_metadata','track_observations'] LOOP
   EXECUTE format('CREATE POLICY %I ON ranking_storage.%I AS %s FOR SELECT TO %s USING (%s)',p.polname,destination,
    CASE WHEN p.polpermissive THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END,roles,pg_get_expr(p.polqual,p.polrelid));
  END LOOP;
 END LOOP;
END $$;
CREATE VIEW public.track_rankings WITH(security_invoker=true) AS
 SELECT o.id, o.snapshot_id, o.user_id, m.track_id, m.track_name, m.track_image_url, m.artist_id, m.artist_name, m.album_id, m.album_name, m.duration_ms, o.popularity, o.rank, o.created_at, o.previous_rank FROM ranking_storage.track_observations o
 JOIN ranking_storage.track_metadata m ON m.metadata_key=o.metadata_key AND m.user_id=o.user_id;
ALTER VIEW public.track_rankings OWNER TO postgres;
GRANT SELECT ON ranking_storage.track_metadata, ranking_storage.track_observations TO anon,authenticated,service_role;
-- No schema USAGE or physical write grants to API roles. PostgreSQL resolves
-- the underlying view relations at creation; security-invoker RLS still applies.
DO $$ DECLARE d record; a record;
BEGIN
 FOR d IN SELECT attname,pg_get_expr(adbin,adrelid) AS expression FROM pg_attrdef JOIN pg_attribute
  ON adrelid=attrelid AND adnum=attnum WHERE adrelid='ranking_storage_backup.track_rankings'::regclass LOOP
  EXECUTE format('ALTER VIEW public.track_rankings ALTER COLUMN %I SET DEFAULT %s',d.attname,d.expression);
 END LOOP;
 FOR a IN SELECT x.* FROM pg_class c CROSS JOIN LATERAL aclexplode(c.relacl) x
  WHERE c.oid='ranking_storage_backup.track_rankings'::regclass LOOP
  EXECUTE format('GRANT %s ON public.track_rankings TO %s%s',a.privilege_type,
   CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE quote_ident(a.grantee::regrole::text) END,
   CASE WHEN a.is_grantable THEN ' WITH GRANT OPTION' ELSE '' END);
 END LOOP;
END $$;

CREATE FUNCTION ranking_storage.write_track() RETURNS trigger
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
DECLARE v_privileged boolean := ranking_storage.caller_bypasses_rls();
 v_metadata integer; v_hash bytea; v_collision integer; v_id uuid;
 v_current public.track_rankings%ROWTYPE;
BEGIN
 IF current_setting('transaction_isolation') <> 'read committed' THEN
  RAISE EXCEPTION 'Ranking writes require READ COMMITTED isolation' USING ERRCODE='0A000';
 END IF;
 -- Match original INSERT/DELETE ownership and the absence of an UPDATE policy.
 IF NOT v_privileged THEN
  IF TG_OP='UPDATE' THEN RETURN NULL; END IF;
  IF TG_OP='DELETE' AND (auth.uid() IS NULL OR OLD.user_id IS DISTINCT FROM auth.uid()) THEN RETURN NULL; END IF;
  IF TG_OP='INSERT' AND (auth.uid() IS NULL OR NEW.user_id IS DISTINCT FROM auth.uid()) THEN
   RAISE EXCEPTION 'new row violates row-level security policy for track_rankings' USING ERRCODE='42501';
  END IF;
 END IF;
 PERFORM ranking_storage.lock_write(
  ARRAY[CASE WHEN TG_OP<>'DELETE' THEN NEW.user_id END,CASE WHEN TG_OP<>'INSERT' THEN OLD.user_id END],
  ARRAY[CASE WHEN TG_OP<>'DELETE' THEN NEW.snapshot_id END,CASE WHEN TG_OP<>'INSERT' THEN OLD.snapshot_id END]);
 IF TG_OP IN ('DELETE','UPDATE') THEN
  SELECT o.id, o.snapshot_id, o.user_id, m.track_id, m.track_name, m.track_image_url, m.artist_id, m.artist_name, m.album_id, m.album_name, m.duration_ms, o.popularity, o.rank, o.created_at, o.previous_rank INTO v_current FROM ranking_storage.track_observations o
   JOIN ranking_storage.track_metadata m ON m.metadata_key=o.metadata_key AND m.user_id=o.user_id
   WHERE o.id=OLD.id FOR UPDATE OF o;
  IF NOT FOUND THEN RETURN NULL; END IF;
  IF v_current IS DISTINCT FROM OLD THEN
   RAISE EXCEPTION 'Ranking changed concurrently; retry transaction' USING ERRCODE='40001';
  END IF;
 END IF;
 IF TG_OP='DELETE' THEN
  DELETE FROM ranking_storage.track_observations WHERE id=OLD.id RETURNING id INTO v_id;
  IF v_id IS NULL THEN RETURN NULL; END IF;
  RETURN OLD;
 END IF;
 v_hash := ranking_storage.track_fingerprint(NEW.track_id, NEW.track_name, NEW.track_image_url, NEW.artist_id, NEW.artist_name, NEW.album_id, NEW.album_name, NEW.duration_ms);
 -- Separate statement after the lock gives a fresh READ COMMITTED snapshot.
 SELECT metadata_key INTO v_metadata FROM ranking_storage.track_metadata m
 WHERE m.user_id=NEW.user_id AND m.metadata_hash=v_hash AND m.track_id IS NOT DISTINCT FROM NEW.track_id AND m.track_name IS NOT DISTINCT FROM NEW.track_name AND m.track_image_url IS NOT DISTINCT FROM NEW.track_image_url AND m.artist_id IS NOT DISTINCT FROM NEW.artist_id AND m.artist_name IS NOT DISTINCT FROM NEW.artist_name AND m.album_id IS NOT DISTINCT FROM NEW.album_id AND m.album_name IS NOT DISTINCT FROM NEW.album_name AND m.duration_ms IS NOT DISTINCT FROM NEW.duration_ms;
 IF v_metadata IS NULL THEN
  SELECT coalesce(max(collision)+1,0) INTO v_collision FROM ranking_storage.track_metadata
   WHERE user_id=NEW.user_id AND metadata_hash=v_hash;
  BEGIN
   INSERT INTO ranking_storage.track_metadata(user_id,track_id, track_name, track_image_url, artist_id, artist_name, album_id, album_name, duration_ms,collision)
   VALUES(NEW.user_id,NEW.track_id, NEW.track_name, NEW.track_image_url, NEW.artist_id, NEW.artist_name, NEW.album_id, NEW.album_name, NEW.duration_ms,v_collision) RETURNING metadata_key INTO v_metadata;
  EXCEPTION WHEN unique_violation THEN
   -- Fail atomically if a concurrent administrative writer bypasses this lock.
   RAISE EXCEPTION 'concurrent metadata change; retry transaction' USING ERRCODE='40001';
  END;
 END IF;
 IF TG_OP='INSERT' THEN
  INSERT INTO ranking_storage.track_observations(id, snapshot_id, user_id, created_at, metadata_key, popularity, rank, previous_rank) VALUES(NEW.id, NEW.snapshot_id, NEW.user_id, NEW.created_at, v_metadata, NEW.popularity, NEW.rank, NEW.previous_rank);
 ELSE
  UPDATE ranking_storage.track_observations SET id=NEW.id, snapshot_id=NEW.snapshot_id, user_id=NEW.user_id, created_at=NEW.created_at, metadata_key=v_metadata, popularity=NEW.popularity, rank=NEW.rank, previous_rank=NEW.previous_rank WHERE id=OLD.id RETURNING id INTO v_id;
  IF v_id IS NULL THEN RETURN NULL; END IF;
 END IF;
 RETURN NEW;
END $$;
ALTER FUNCTION ranking_storage.write_track() OWNER TO postgres;
REVOKE ALL ON FUNCTION ranking_storage.write_track() FROM PUBLIC;
CREATE TRIGGER write_track_ranking INSTEAD OF INSERT OR UPDATE OR DELETE ON public.track_rankings
 FOR EACH ROW EXECUTE FUNCTION ranking_storage.write_track();

CREATE FUNCTION ranking_storage.prune_track() RETURNS trigger
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
BEGIN
 IF current_setting('transaction_isolation') <> 'read committed' THEN
  RAISE EXCEPTION 'Ranking deletion requires READ COMMITTED isolation' USING ERRCODE='0A000';
 END IF;
 IF TG_OP='UPDATE' AND OLD.metadata_key=NEW.metadata_key AND OLD.user_id=NEW.user_id THEN RETURN NULL; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('ranking-storage:'||OLD.user_id::text,0));
 DELETE FROM ranking_storage.track_metadata m WHERE m.metadata_key=OLD.metadata_key
 AND NOT EXISTS(SELECT 1 FROM ranking_storage.track_observations o WHERE o.metadata_key=m.metadata_key);
 RETURN NULL;
END $$;
ALTER FUNCTION ranking_storage.prune_track() OWNER TO postgres;
REVOKE ALL ON FUNCTION ranking_storage.prune_track() FROM PUBLIC;
CREATE TRIGGER prune_track_metadata AFTER DELETE OR UPDATE ON ranking_storage.track_observations
 FOR EACH ROW EXECUTE FUNCTION ranking_storage.prune_track();

DO $$ BEGIN
 IF EXISTS((SELECT * FROM ranking_storage_backup.track_rankings EXCEPT ALL SELECT * FROM public.track_rankings)
  UNION ALL (SELECT * FROM public.track_rankings EXCEPT ALL SELECT * FROM ranking_storage_backup.track_rankings))
 THEN RAISE EXCEPTION 'Exact reconstruction failed: track_rankings'; END IF;
END $$;


-- album: fail closed on an already migrated or unexpected source contract.
DO $$ BEGIN
  IF md5(jsonb_build_object(
 'columns',(SELECT jsonb_agg(jsonb_build_array(a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull,a.attidentity,a.attgenerated,pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid=d.adrelid AND a.attnum=d.adnum WHERE a.attrelid='public.album_rankings'::regclass AND a.attnum>0 AND NOT a.attisdropped),
 'constraints',(SELECT jsonb_agg(jsonb_build_array(c.contype,pg_get_constraintdef(c.oid),c.convalidated,c.condeferrable,c.condeferred) ORDER BY c.contype,pg_get_constraintdef(c.oid)) FROM pg_constraint c WHERE c.conrelid='public.album_rankings'::regclass),
 'policies',(SELECT jsonb_agg(jsonb_build_array(p.polname,p.polcmd,p.polpermissive,(SELECT jsonb_agg(CASE WHEN x=0 THEN 'public' ELSE x::regrole::text END ORDER BY x::regrole::text) FROM unnest(p.polroles)x),pg_get_expr(p.polqual,p.polrelid),pg_get_expr(p.polwithcheck,p.polrelid)) ORDER BY p.polname) FROM pg_policy p WHERE p.polrelid='public.album_rankings'::regclass),
 'rls',(SELECT jsonb_build_array(relrowsecurity,relforcerowsecurity) FROM pg_class WHERE oid='public.album_rankings'::regclass)
)::text) <> '52df36b1613d4f820fca5fcd8bc9c7b0' THEN
    RAISE EXCEPTION 'Source schema or policies changed: album_rankings; re-audit before migrating';
  END IF;
  IF (SELECT relkind FROM pg_class WHERE oid='public.album_rankings'::regclass) <> 'r'
    OR (SELECT array_agg(attname::text ORDER BY attnum) FROM pg_attribute
        WHERE attrelid='public.album_rankings'::regclass AND attnum>0 AND NOT attisdropped) <> ARRAY['id', 'snapshot_id', 'user_id', 'album_id', 'album_name', 'album_image_url', 'artist_id', 'artist_name', 'release_date', 'total_tracks', 'track_count', 'rank', 'created_at', 'previous_rank']::text[]
    OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='public.album_rankings'::regclass AND polcmd IN ('w','*'))
    OR EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='public.album_rankings'::regclass AND NOT tgisinternal)
    OR EXISTS(SELECT 1 FROM pg_constraint WHERE contype='f' AND confrelid='public.album_rankings'::regclass)
    OR EXISTS(SELECT 1 FROM pg_publication_tables WHERE schemaname='public' AND tablename='album_rankings')
    OR EXISTS(SELECT 1 FROM pg_depend d WHERE d.refclassid='pg_class'::regclass
       AND d.refobjid='public.album_rankings'::regclass AND d.classid IN ('pg_rewrite'::regclass,'pg_proc'::regclass))
    OR EXISTS(SELECT 1 FROM pg_depend d WHERE d.refclassid='pg_type'::regclass
       AND d.refobjid=(SELECT reltype FROM pg_class WHERE oid='public.album_rankings'::regclass)
       AND d.classid='pg_proc'::regclass)
  THEN RAISE EXCEPTION 'Unexpected album_rankings contract; inspect before migrating'; END IF;
END $$;
ALTER TABLE public.album_rankings SET SCHEMA ranking_storage_backup;

CREATE FUNCTION ranking_storage.album_fingerprint(p_album_id text, p_album_name text, p_album_image_url text, p_artist_id text, p_artist_name text, p_release_date text, p_total_tracks integer) RETURNS bytea
LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,pg_temp AS $$
 SELECT sha256(convert_to(jsonb_build_array(p_album_id, p_album_name, p_album_image_url, p_artist_id, p_artist_name, p_release_date, p_total_tracks)::text,'UTF8'))
$$;
REVOKE ALL ON FUNCTION ranking_storage.album_fingerprint FROM PUBLIC;
ALTER FUNCTION ranking_storage.album_fingerprint OWNER TO postgres;
CREATE TABLE ranking_storage.album_metadata (
 metadata_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 album_id text NOT NULL, album_name text NOT NULL, album_image_url text, artist_id text NOT NULL, artist_name text NOT NULL, release_date text, total_tracks integer,
 metadata_hash bytea GENERATED ALWAYS AS (ranking_storage.album_fingerprint(album_id, album_name, album_image_url, artist_id, artist_name, release_date, total_tracks)) STORED,
 collision integer NOT NULL DEFAULT 0,
 UNIQUE (metadata_key,user_id), UNIQUE (user_id,metadata_hash,collision)
);
CREATE INDEX ON ranking_storage.album_metadata(user_id,album_id);
CREATE TABLE ranking_storage.album_observations (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 snapshot_id uuid NOT NULL REFERENCES public.snapshots(id) ON DELETE CASCADE,
 user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
 created_at timestamptz NOT NULL DEFAULT now(),
 metadata_key integer NOT NULL,
 track_count integer NOT NULL DEFAULT 1, rank integer NOT NULL CHECK (rank >= 1), previous_rank integer,
 FOREIGN KEY(metadata_key,user_id) REFERENCES ranking_storage.album_metadata(metadata_key,user_id)
);
ALTER TABLE ranking_storage.album_metadata OWNER TO postgres;
ALTER TABLE ranking_storage.album_observations OWNER TO postgres;

-- Distinct typed metadata preserves NULLs and PostgreSQL array bounds. A digest
-- only selects a bucket; collisions use another discriminator, never wrong data.
INSERT INTO ranking_storage.album_metadata(user_id,album_id, album_name, album_image_url, artist_id, artist_name, release_date, total_tracks,collision)
 SELECT user_id,album_id, album_name, album_image_url, artist_id, artist_name, release_date, total_tracks,(row_number() OVER (PARTITION BY user_id,
 ranking_storage.album_fingerprint(album_id, album_name, album_image_url, artist_id, artist_name, release_date, total_tracks))-1)::integer
 FROM (SELECT DISTINCT user_id,album_id, album_name, album_image_url, artist_id, artist_name, release_date, total_tracks FROM ranking_storage_backup.album_rankings) d;
INSERT INTO ranking_storage.album_observations(id, snapshot_id, user_id, created_at, metadata_key, track_count, rank, previous_rank)
 SELECT r.id, r.snapshot_id, r.user_id, r.created_at, m.metadata_key, r.track_count, r.rank, r.previous_rank
 FROM ranking_storage_backup.album_rankings r JOIN ranking_storage.album_metadata m
 ON m.user_id=r.user_id AND m.metadata_hash=ranking_storage.album_fingerprint(r.album_id, r.album_name, r.album_image_url, r.artist_id, r.artist_name, r.release_date, r.total_tracks)
 AND m.album_id IS NOT DISTINCT FROM r.album_id AND m.album_name IS NOT DISTINCT FROM r.album_name AND m.album_image_url IS NOT DISTINCT FROM r.album_image_url AND m.artist_id IS NOT DISTINCT FROM r.artist_id AND m.artist_name IS NOT DISTINCT FROM r.artist_name AND m.release_date IS NOT DISTINCT FROM r.release_date AND m.total_tracks IS NOT DISTINCT FROM r.total_tracks;

-- Build narrow indexes after the bulk copy. Repeated snapshot/owner/metadata
-- keys can use B-tree deduplication; sorting one snapshot's 50 rows is cheap.
ALTER TABLE ranking_storage.album_observations ADD PRIMARY KEY(id);
CREATE INDEX ON ranking_storage.album_observations(snapshot_id);
CREATE INDEX ON ranking_storage.album_observations(user_id);
CREATE INDEX ON ranking_storage.album_observations(metadata_key);

ALTER TABLE ranking_storage.album_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE ranking_storage.album_observations ENABLE ROW LEVEL SECURITY;
-- Preserve the exact live SELECT policies, including restrictive privacy rules.
DO $$ DECLARE p record; roles text; destination text;
BEGIN
 FOR p IN SELECT * FROM pg_policy WHERE polrelid='ranking_storage_backup.album_rankings'::regclass AND polcmd='r' LOOP
  SELECT string_agg(CASE WHEN x=0 THEN 'PUBLIC' ELSE quote_ident(x::regrole::text) END,',') INTO roles FROM unnest(p.polroles) x;
  FOREACH destination IN ARRAY ARRAY['album_metadata','album_observations'] LOOP
   EXECUTE format('CREATE POLICY %I ON ranking_storage.%I AS %s FOR SELECT TO %s USING (%s)',p.polname,destination,
    CASE WHEN p.polpermissive THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END,roles,pg_get_expr(p.polqual,p.polrelid));
  END LOOP;
 END LOOP;
END $$;
CREATE VIEW public.album_rankings WITH(security_invoker=true) AS
 SELECT o.id, o.snapshot_id, o.user_id, m.album_id, m.album_name, m.album_image_url, m.artist_id, m.artist_name, m.release_date, m.total_tracks, o.track_count, o.rank, o.created_at, o.previous_rank FROM ranking_storage.album_observations o
 JOIN ranking_storage.album_metadata m ON m.metadata_key=o.metadata_key AND m.user_id=o.user_id;
ALTER VIEW public.album_rankings OWNER TO postgres;
GRANT SELECT ON ranking_storage.album_metadata, ranking_storage.album_observations TO anon,authenticated,service_role;
-- No schema USAGE or physical write grants to API roles. PostgreSQL resolves
-- the underlying view relations at creation; security-invoker RLS still applies.
DO $$ DECLARE d record; a record;
BEGIN
 FOR d IN SELECT attname,pg_get_expr(adbin,adrelid) AS expression FROM pg_attrdef JOIN pg_attribute
  ON adrelid=attrelid AND adnum=attnum WHERE adrelid='ranking_storage_backup.album_rankings'::regclass LOOP
  EXECUTE format('ALTER VIEW public.album_rankings ALTER COLUMN %I SET DEFAULT %s',d.attname,d.expression);
 END LOOP;
 FOR a IN SELECT x.* FROM pg_class c CROSS JOIN LATERAL aclexplode(c.relacl) x
  WHERE c.oid='ranking_storage_backup.album_rankings'::regclass LOOP
  EXECUTE format('GRANT %s ON public.album_rankings TO %s%s',a.privilege_type,
   CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE quote_ident(a.grantee::regrole::text) END,
   CASE WHEN a.is_grantable THEN ' WITH GRANT OPTION' ELSE '' END);
 END LOOP;
END $$;

CREATE FUNCTION ranking_storage.write_album() RETURNS trigger
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
DECLARE v_privileged boolean := ranking_storage.caller_bypasses_rls();
 v_metadata integer; v_hash bytea; v_collision integer; v_id uuid;
 v_current public.album_rankings%ROWTYPE;
BEGIN
 IF current_setting('transaction_isolation') <> 'read committed' THEN
  RAISE EXCEPTION 'Ranking writes require READ COMMITTED isolation' USING ERRCODE='0A000';
 END IF;
 -- Match original INSERT/DELETE ownership and the absence of an UPDATE policy.
 IF NOT v_privileged THEN
  IF TG_OP='UPDATE' THEN RETURN NULL; END IF;
  IF TG_OP='DELETE' AND (auth.uid() IS NULL OR OLD.user_id IS DISTINCT FROM auth.uid()) THEN RETURN NULL; END IF;
  IF TG_OP='INSERT' AND (auth.uid() IS NULL OR NEW.user_id IS DISTINCT FROM auth.uid()) THEN
   RAISE EXCEPTION 'new row violates row-level security policy for album_rankings' USING ERRCODE='42501';
  END IF;
 END IF;
 PERFORM ranking_storage.lock_write(
  ARRAY[CASE WHEN TG_OP<>'DELETE' THEN NEW.user_id END,CASE WHEN TG_OP<>'INSERT' THEN OLD.user_id END],
  ARRAY[CASE WHEN TG_OP<>'DELETE' THEN NEW.snapshot_id END,CASE WHEN TG_OP<>'INSERT' THEN OLD.snapshot_id END]);
 IF TG_OP IN ('DELETE','UPDATE') THEN
  SELECT o.id, o.snapshot_id, o.user_id, m.album_id, m.album_name, m.album_image_url, m.artist_id, m.artist_name, m.release_date, m.total_tracks, o.track_count, o.rank, o.created_at, o.previous_rank INTO v_current FROM ranking_storage.album_observations o
   JOIN ranking_storage.album_metadata m ON m.metadata_key=o.metadata_key AND m.user_id=o.user_id
   WHERE o.id=OLD.id FOR UPDATE OF o;
  IF NOT FOUND THEN RETURN NULL; END IF;
  IF v_current IS DISTINCT FROM OLD THEN
   RAISE EXCEPTION 'Ranking changed concurrently; retry transaction' USING ERRCODE='40001';
  END IF;
 END IF;
 IF TG_OP='DELETE' THEN
  DELETE FROM ranking_storage.album_observations WHERE id=OLD.id RETURNING id INTO v_id;
  IF v_id IS NULL THEN RETURN NULL; END IF;
  RETURN OLD;
 END IF;
 v_hash := ranking_storage.album_fingerprint(NEW.album_id, NEW.album_name, NEW.album_image_url, NEW.artist_id, NEW.artist_name, NEW.release_date, NEW.total_tracks);
 -- Separate statement after the lock gives a fresh READ COMMITTED snapshot.
 SELECT metadata_key INTO v_metadata FROM ranking_storage.album_metadata m
 WHERE m.user_id=NEW.user_id AND m.metadata_hash=v_hash AND m.album_id IS NOT DISTINCT FROM NEW.album_id AND m.album_name IS NOT DISTINCT FROM NEW.album_name AND m.album_image_url IS NOT DISTINCT FROM NEW.album_image_url AND m.artist_id IS NOT DISTINCT FROM NEW.artist_id AND m.artist_name IS NOT DISTINCT FROM NEW.artist_name AND m.release_date IS NOT DISTINCT FROM NEW.release_date AND m.total_tracks IS NOT DISTINCT FROM NEW.total_tracks;
 IF v_metadata IS NULL THEN
  SELECT coalesce(max(collision)+1,0) INTO v_collision FROM ranking_storage.album_metadata
   WHERE user_id=NEW.user_id AND metadata_hash=v_hash;
  BEGIN
   INSERT INTO ranking_storage.album_metadata(user_id,album_id, album_name, album_image_url, artist_id, artist_name, release_date, total_tracks,collision)
   VALUES(NEW.user_id,NEW.album_id, NEW.album_name, NEW.album_image_url, NEW.artist_id, NEW.artist_name, NEW.release_date, NEW.total_tracks,v_collision) RETURNING metadata_key INTO v_metadata;
  EXCEPTION WHEN unique_violation THEN
   -- Fail atomically if a concurrent administrative writer bypasses this lock.
   RAISE EXCEPTION 'concurrent metadata change; retry transaction' USING ERRCODE='40001';
  END;
 END IF;
 IF TG_OP='INSERT' THEN
  INSERT INTO ranking_storage.album_observations(id, snapshot_id, user_id, created_at, metadata_key, track_count, rank, previous_rank) VALUES(NEW.id, NEW.snapshot_id, NEW.user_id, NEW.created_at, v_metadata, NEW.track_count, NEW.rank, NEW.previous_rank);
 ELSE
  UPDATE ranking_storage.album_observations SET id=NEW.id, snapshot_id=NEW.snapshot_id, user_id=NEW.user_id, created_at=NEW.created_at, metadata_key=v_metadata, track_count=NEW.track_count, rank=NEW.rank, previous_rank=NEW.previous_rank WHERE id=OLD.id RETURNING id INTO v_id;
  IF v_id IS NULL THEN RETURN NULL; END IF;
 END IF;
 RETURN NEW;
END $$;
ALTER FUNCTION ranking_storage.write_album() OWNER TO postgres;
REVOKE ALL ON FUNCTION ranking_storage.write_album() FROM PUBLIC;
CREATE TRIGGER write_album_ranking INSTEAD OF INSERT OR UPDATE OR DELETE ON public.album_rankings
 FOR EACH ROW EXECUTE FUNCTION ranking_storage.write_album();

CREATE FUNCTION ranking_storage.prune_album() RETURNS trigger
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
BEGIN
 IF current_setting('transaction_isolation') <> 'read committed' THEN
  RAISE EXCEPTION 'Ranking deletion requires READ COMMITTED isolation' USING ERRCODE='0A000';
 END IF;
 IF TG_OP='UPDATE' AND OLD.metadata_key=NEW.metadata_key AND OLD.user_id=NEW.user_id THEN RETURN NULL; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('ranking-storage:'||OLD.user_id::text,0));
 DELETE FROM ranking_storage.album_metadata m WHERE m.metadata_key=OLD.metadata_key
 AND NOT EXISTS(SELECT 1 FROM ranking_storage.album_observations o WHERE o.metadata_key=m.metadata_key);
 RETURN NULL;
END $$;
ALTER FUNCTION ranking_storage.prune_album() OWNER TO postgres;
REVOKE ALL ON FUNCTION ranking_storage.prune_album() FROM PUBLIC;
CREATE TRIGGER prune_album_metadata AFTER DELETE OR UPDATE ON ranking_storage.album_observations
 FOR EACH ROW EXECUTE FUNCTION ranking_storage.prune_album();

DO $$ BEGIN
 IF EXISTS((SELECT * FROM ranking_storage_backup.album_rankings EXCEPT ALL SELECT * FROM public.album_rankings)
  UNION ALL (SELECT * FROM public.album_rankings EXCEPT ALL SELECT * FROM ranking_storage_backup.album_rankings))
 THEN RAISE EXCEPTION 'Exact reconstruction failed: album_rankings'; END IF;
END $$;


-- Free old data only after all tables passed typed, bidirectional equality.
TRUNCATE ranking_storage_backup.album_rankings,ranking_storage_backup.artist_rankings,ranking_storage_backup.track_rankings;
ALTER FUNCTION ranking_storage.lock_write(uuid[],uuid[]) OWNER TO postgres;
ALTER FUNCTION ranking_storage.caller_bypasses_rls() OWNER TO postgres;
ANALYZE ranking_storage.album_observations; ANALYZE ranking_storage.artist_observations; ANALYZE ranking_storage.track_observations;
ANALYZE ranking_storage.album_metadata; ANALYZE ranking_storage.artist_metadata; ANALYZE ranking_storage.track_metadata;
NOTIFY pgrst,'reload schema';
COMMIT;
